### PR TITLE
fixed remove-expired CLI command error

### LINKED ISSUE #92: garbage collection with console command throws error
console:
```
developer@2f4c8df8a609:/var/htdocs$ bin/console reset-password:remove-expired
Removing expired reset password requests...
Garbage collection successful. Removed 0 reset password request objects.

In Command.php line 258:
                                                                                                                                                      
  Return value of "SymfonyCasts\Bundle\ResetPassword\Command\ResetPasswordRemoveExpiredCommand::execute()" must be of the type int, "NULL" returned.
```
mariadb:
```
MariaDB [reset-password-app-test-2]> select * from reset_password_request;
+----+---------+----------------------+----------------------------------------------+---------------------+---------------------+
| id | user_id | selector             | hashed_token                                 | requested_at        | expires_at          |
+----+---------+----------------------+----------------------------------------------+---------------------+---------------------+
|  1 |       1 | k71rLHlzaCMLklIX26Tm | g65btmYbs3jrf2S7zbyvFds4CPTo8UAs+MGSy9P+xyk= | 2020-04-04 22:08:52 | 2020-04-04 23:08:52 |

```

config:
```
symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    throttle_limit: 0
```

### PR DESCRIPTION
**Pull request by jrushlow**
- command returns `0` upon completion
- refactored success message
- added functional tests for command

fixes #92

### CODE REVIEW

File: tests/FunctionalTests/Command/ResetPasswordRemoveExpiredCommandTest.php [hunk 1]
```diff
@@ -0,0 +1,106 @@
...
+/**
+ * @author Jesse Rushlow <jr@rushlow.dev>
+ * @author Ryan Weaver   <ryan@symfonycasts.com>
+ *
+ * @internal
+ */
+final class ResetPasswordRemoveExpiredCommandTest extends TestCase
+{
+    /**
+     * @var \Doctrine\Common\Persistence\ObjectManager|object
```
Comment (jrushlow) [inline tests/FunctionalTests/Command/ResetPasswordRemoveExpiredCommandTest.php:30]: This ns should be fixed in a separate PR. Related to #75 

I have to bump the `doctrine/doctrine-bundle` version in dev to minimum of `2.0.3` to utilize the new `Doctrine\Persistence\...` namespace.

**Comment by weaverryan** [comment]
Thanks @jrushlow!
