### PR TITLE
RFC: Add translations for exception reasons

### LINKED ISSUE #202: Translation reason
Hi, 

I have a question, there are possibility to translate the reason that return for exceptions :

ResetPasswordExceptionInterface
ExpiredResetPasswordTokenException
FakeRepositoryException
InvalidResetPasswordTokenException
TooManyPasswordRequestsException 

? :)

### PR DESCRIPTION
**Pull request by bocharsky-bw**
Closes #202 

The next step - I'll create a PR in Maker bundle to wrap reasons with `Translator::trans()` - then all exception messages in this bundle will be automatically translated. The remaining step - wait for more translation contributions.

Basically, I explained a workaround here which can be avoided with this PR: https://github.com/SymfonyCasts/reset-password-bundle/issues/202#issuecomment-1024019601

### CODE REVIEW

File: src/Exception/ResetPasswordExceptionInterface.php [hunk 1]
```diff
@@ -14,5 +14,8 @@
  */
 interface ResetPasswordExceptionInterface extends \Throwable
 {
+    public const MESSAGE_PROBLEM_VALIDATE = 'There was a problem validating your password reset request';
+    public const MESSAGE_PROBLEM_HANDLE = 'There was a problem handling your password reset request';
```
Comment (bocharsky-bw) [inline src/Exception/ResetPasswordExceptionInterface.php:18]: Those strings are hardcode in Maker - probably we could migrate them in this bundle as well and then just reuse these constants in Maker, see https://github.com/symfony/maker-bundle/blob/085358c107a7047b4889455d7518d0dbf55169f1/src/Resources/skeleton/resetPassword/ResetPasswordController.tpl.php#L160

**Review by jrushlow — APPROVED** [review]
Awesome! Thanks @bocharsky-bw

**Comment by bocharsky-bw** [comment]
Related PR to Maker bundle created: https://github.com/symfony/maker-bundle/pull/1059
